name: BetterPlayerVaults
version: "1.0"
main: software.bigbade.playervaults.BetterPlayerVaults
commands:
  playervault:
    description: Opens a player's vault
    usage: /playervault (number)
    aliases:
      - pv
      - vault
  clearvault:
    description: Clears a player's vault
    usage: /clearvault (player) (number)
    aliases:
      - clearvault
      - deletevault
permissions:
  betterplayervaults.open:
    description: Allows the player to open vaults
    default: true
  betterplayervaults.snoop:
    description: Allows the player to snoop in vaults
    default: false
  betterplayervaults.clear:
    description: Allows the player to clear vaults
    default: false
